# Generated by Django 4.0.4 on 2022-05-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=10)),
                ('domanda', models.CharField(max_length=15)),
                ('risposta', models.CharField(max_length=15)),
            ],
        ),
    ]
