# Generated by Django 4.0.4 on 2022-05-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='domanda',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='faq',
            name='risposta',
            field=models.CharField(max_length=100),
        ),
    ]
