# Generated by Django 4.0.4 on 2022-05-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_alter_faq_domanda_alter_faq_risposta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='nome',
            field=models.CharField(max_length=50),
        ),
    ]
