# Generated by Django 4.0.4 on 2022-05-07 14:55

import django.core.validators
from django.db import migrations, models
import prodotto.models


class Migration(migrations.Migration):

    dependencies = [
        ('prodotto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodotto',
            name='nome',
            field=models.CharField(help_text='Nome', max_length=10, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='prodotto',
            name='prezzo',
            field=models.FloatField(help_text='Prezzo', max_length=3, validators=[prodotto.models.validate_price, django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)], verbose_name='Prezzo'),
        ),
    ]
