# Generated by Django 4.0.4 on 2022-05-11 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prodotto', '0002_alter_prodotto_nome_alter_prodotto_prezzo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prodotto',
            options={'verbose_name': 'Prodotto', 'verbose_name_plural': 'Prodotti'},
        ),
    ]
