# Generated by Django 4.0.4 on 2022-05-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appuntamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, help_text='Nome appuntamento', max_length=20, null=True, verbose_name='Nome appuntamento')),
                ('data', models.DateField(help_text='Giorno evento', verbose_name='Data evento')),
                ('orario_inizio', models.TimeField(help_text='Orario di inizio', verbose_name='Orario di inizio')),
                ('orario_fine', models.TimeField(help_text='Orario di fine', verbose_name='Orario di fine')),
                ('note', models.TextField(blank=True, help_text='Nome', null=True, verbose_name='Note')),
            ],
            options={
                'verbose_name': 'Scheduling',
                'verbose_name_plural': 'Scheduling',
            },
        ),
    ]
