# Generated by Django 4.0.4 on 2022-05-06 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appuntamento',
            options={'verbose_name': 'Appuntamento', 'verbose_name_plural': 'Appuntamenti'},
        ),
        migrations.RenameField(
            model_name='appuntamento',
            old_name='data',
            new_name='day',
        ),
    ]
