# Generated by Django 4.0.4 on 2022-05-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_alter_appuntamento_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuntamento',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
