# Generated by Django 4.0.4 on 2022-05-07 16:20

from django.db import migrations, models
import django.db.models.deletion
import fattura.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fattura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('cognome', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('nome_ditta', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('citta', models.CharField(max_length=15)),
                ('via', models.CharField(default=None, max_length=25)),
                ('num_civico', models.IntegerField(default=None)),
                ('cap', models.BigIntegerField(default=None)),
                ('partita_iva', models.BigIntegerField(blank=True, default=None, null=True)),
                ('cod_fiscale', models.CharField(blank=True, default=None, max_length=16, null=True)),
                ('cod_cliente', models.CharField(blank=True, max_length=7, null=True)),
                ('numero', models.IntegerField()),
                ('data', models.DateField()),
                ('descrizione_pag', models.TextField(blank=True, max_length=20, null=True)),
                ('banca', models.CharField(blank=True, max_length=27, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TariffaFatt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione_prod', models.TextField(blank=True, null=True)),
                ('quantita', models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True)),
                ('prezzo', models.FloatField(blank=True, max_length=6, null=True, validators=[fattura.models.validate_price])),
                ('fatt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fattura.fattura')),
            ],
        ),
    ]
