# Generated by Django 4.0.4 on 2022-05-11 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fattura', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fattura',
            options={'verbose_name': 'Fattura', 'verbose_name_plural': 'Fatture'},
        ),
    ]
