# Generated by Django 4.0.4 on 2022-05-11 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tariffa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tariffa',
            options={'verbose_name': 'Tariffa', 'verbose_name_plural': 'Tariffe'},
        ),
    ]
